/**
 * Single icon library (lucide) mapped to string keys so content data stays
 * serialisable. Add new keys here rather than importing icons in data files.
 */
import {
  Activity,
  Apple,
  Armchair,
  ArrowRight,
  Baby,
  BadgeCheck,
  Bot,
  Brain,
  Brush,
  Building2,
  ChartColumnIncreasing,
  CalendarDays,
  ClipboardList,
  Coffee,
  Cpu,
  Droplet,
  Ear,
  Eye,
  FlaskConical,
  Flower2,
  Gauge,
  GraduationCap,
  Guitar,
  Hand,
  HandHeart,
  HeartPulse,
  Layers,
  Mic,
  Music,
  Orbit,
  Palette,
  PartyPopper,
  Pill,
  Presentation,
  Receipt,
  Route,
  Scale,
  Shield,
  ShieldPlus,
  Smile,
  Sparkle,
  Sparkles,
  Sprout,
  Stethoscope,
  Tent,
  Timer,
  User,
  Users,
  AudioLines,
  Wallet,
  Wind,
  type LucideIcon,
} from 'lucide-react'

export const ICONS = {
  activity: Activity,
  apple: Apple,
  armchair: Armchair,
  arrowRight: ArrowRight,
  audio: AudioLines,
  baby: Baby,
  badgeCheck: BadgeCheck,
  bot: Bot,
  brain: Brain,
  brush: Brush,
  building: Building2,
  calendarDot: CalendarDays,
  chart: ChartColumnIncreasing,
  clipboard: ClipboardList,
  coffee: Coffee,
  cpu: Cpu,
  droplet: Droplet,
  ear: Ear,
  eye: Eye,
  flask: FlaskConical,
  flower: Flower2,
  gauge: Gauge,
  graduation: GraduationCap,
  guitar: Guitar,
  hand: Hand,
  heartHand: HandHeart,
  heartPulse: HeartPulse,
  layers: Layers,
  mic: Mic,
  music: Music,
  orbit: Orbit,
  palette: Palette,
  party: PartyPopper,
  pill: Pill,
  presentation: Presentation,
  receipt: Receipt,
  route: Route,
  scale: Scale,
  shield: Shield,
  shieldPlus: ShieldPlus,
  smile: Smile,
  sparkle: Sparkle,
  sparkles: Sparkles,
  sprout: Sprout,
  stethoscope: Stethoscope,
  tent: Tent,
  timer: Timer,
  user: User,
  users: Users,
  wallet: Wallet,
  wind: Wind,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export function getIcon(name: IconName): LucideIcon {
  return ICONS[name]
}
